name: Upload to FTP
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.5.0
      - uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          protocol: ftps
          local-dir: ./
          server-dir: /var/www/juzoyena.cc/
          state-name: .htsync
          server: ssh.juzoyena.cc
          port: 22
          username: admin
          password: ${{ secrets.FTP_PASSWORD }}
       
